# Generated by Django 2.0.7 on 2018-08-15 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180815_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.VoteReceiver'),
        ),
    ]
