# Generated by Django 2.0.7 on 2018-08-03 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hasker.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.SmallIntegerField(choices=[(-1, 'down'), (0, 'none'), (1, 'up')])),
                ('author', models.ForeignKey(on_delete=models.SET(hasker.profiles.models.get_stub_user), related_name='votes', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
