# Generated by Django 2.0.7 on 2018-08-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(-1, 'down'), (0, 'none'), (1, 'up')], default=0),
        ),
    ]
